### PR TITLE
link vcruntime for MSVC2015

### PR DESCRIPTION
**Pull request by grlee77**
This PR builds off of #10, but adds a patch to try linking vcruntime for MSVC2015

### CODE REVIEW

**Comment by grlee77** [comment]
looks like this did fix the MSVC2015 build, but apparently my attempt to only add the lib on MSVC2015 didn't work because vcruntime lib seems to also be getting added in the MSVC2008 build.

I am not a CMAKE or MSVC expert, so it is very possible there is a better way to do this.

**Comment by grlee77** [comment]
I fixed the MSVC_VERSION check to be >= 1900 so it only adds vcruntime.lib for MSVC2015+.

**Comment by grlee77** [comment]
I'm not sure if there is any easier way to include the missing lib via the CMAKE command line and avoid the patch?

**Comment by dschreij** [comment]
Wow, thanks for looking into this! I think patching the CMakeList.txt is a legitimate solution in this case.  This is supplied with SDL2 itself, and 2.0.8 might just be too old already. So this may be fixed in future versions of SDL2, but for now, if it works then it's all good with me.

**Pull request merged**
