### PR TITLE
Bump sdl2 version to 2.0.12.

### PR DESCRIPTION
**Pull request by matham**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matham** [comment]
@conda-forge-admin, please rerender

**Comment by matham** [comment]
Trying this patch for osx: https://bugzilla.libsdl.org/show_bug.cgi?id=5306.

**Comment by matham** [comment]
The patch doesn't apply directly on 2.0.12. Some intermediate changes need to be included.

**Comment by matham** [comment]
I used the wrong patch initially, should be fixed now.

**Review by dschreij — APPROVED** [review]

**Comment by dschreij** [comment]
Looks good. Do we mind that the license file is not packaged?

**Comment by matham** [comment]
Looks like the license file is being packaged. I didn't check it because I wasn't sure, but we list the correct file in the recipe. But I fixed the license ID.

**Pull request merged**
