### PR TITLE
Bump version to 2.0.20

### PR DESCRIPTION
**Pull request by traversaro**
Build on top of https://github.com/conda-forge/sdl2-feedstock/pull/23 with backport of https://github.com/libsdl-org/SDL/commit/ea0bca573da796268900e53d74541dfe279bb662, that is the fix for https://github.com/libsdl-org/SDL/issues/5208 .
Fix https://github.com/conda-forge/sdl2-feedstock/pull/23 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge/sdl2 the PR is ready for review.

**Review by matham — APPROVED** [review]

**Comment by matham** [comment]
@conda-forge-admin, please rerender

**Comment by matham** [comment]
Sorry. Looks like my merge of the other PR broke it. Can you please fix the conflicts (or create new PR)?

**Comment by traversaro** [comment]
> Sorry. Looks like my merge of the other PR broke it. Can you please fix the conflicts (or create new PR)?

Sorry, I had missed your comment!

**Comment by traversaro** [comment]
Superseded by https://github.com/conda-forge/sdl2-feedstock/pull/27 .

**Pull request closed without merging**
