### PR TITLE
Increase the sdl2 version

### PR DESCRIPTION
**Pull request by matham**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is bumping the sdl2 version to the most recent release.

### CODE REVIEW

**Comment by matham** [comment]
@conda-forge-admin, please rerender

**Comment by matham** [comment]
Ok, it's finally working! Phew. When merging, please squash the commits.

There were 3 changes needed:
* For osx we needed to add `LDFLAGS="-framework ForceFeedback"` as otherwise some newly added function that call this framework by sdl's joystick is not able to link. I guess this is actually a sdl2 bug.
* A previous test disabled directx on windows `if "%PY_VER%"=="2.7"`. This should be `if "%VS_MAJOR%"=="9"` because apparently we're running vs2008 even if it's not python 2.7!? So it failed to disable directx in this case.
* The most recent sdl2 joystick initializes a empty array at https://github.com/spurious/SDL-mirror/blob/master/src/joystick/SDL_joystick.c#L79 because none of the supposed items in the array are enabled. It seems that vs2008 cannot handle it and raises a syntaxerror. I fixed it by adding a patch that adds a `NULL` item to the array so it's never empty. Of course I also patched all places that uses the array to handle the `NULL`.

**Comment by matham** [comment]
Before merging, the issues faced in https://github.com/conda-forge/sdl2_ttf-feedstock/pull/4 should be resolved because I'm suspicious why the appveyor vs2008 is actually installing python 3.6??? Shouldn't it use 2.7?

**Comment by dschreij** [comment]
Thanks for working on this! So I should wait for sdl2_ttf to be fixed before merging this? This is a depedency *for* sdl2_ttf, not *of* so I think we should be fine if I merge this before that feedstock is fixed...

**Comment by matham** [comment]
Yeah, TTF is not a dependency, but even in this recipe it used vs2008 with python 3.6 which doesn't seem right. There doesn't seem to be a 2.7 test and for 3.6 it should use vs2015. 

So we should make sure this is correct and not a bug in the packaging systems. Hopefully there's someone in the know that can clarify?

**Comment by dschreij** [comment]
@conda-forge/core, any suggestions for this problem? Are we doing something wrong that py3.6 is used instead of py2.7 when using vs2008?
@matham I'll wait with merging this until we know more.

**Comment by isuruf** [comment]
Since this recipe is not using python `PY_VER` env variable may be incorrect. using `VS_MAJOR` is the correcy way.

**Comment by dschreij** [comment]
@isuruf Thanks for looking into this. But that's exactly what is happening now right? All references to PY_VER have been changed to the corresponding VS_MAJOR, and the wrong Python/VS version is still used (@matham correct me if I'm wrong)

**Comment by isuruf** [comment]
> and the wrong Python/VS version is still used

where is the wrong version used?

**Comment by matham** [comment]
@isuruf The issue is more clearly displayed here: https://github.com/conda-forge/sdl2_ttf-feedstock/pull/4. It's using vs2008 so `vc` is pinned to 9 - as expected. 

But, in the [test requirement section](https://github.com/conda-forge/sdl2_ttf-feedstock/blob/master/recipe/meta.yaml#L34) it lists `python {{ environ['PY_VER'] + '*' }}  # [win]`. This seems to result in it trying to install python 3.6 and not 2.7 with dependencies `python=3.6 -> vc[version='>=14,<15.0a0']`. That is incompatible with `vc=9`. So the question is, in the `vs2008` test case, why is it installing 3.6?

**Comment by isuruf** [comment]
Ah. You can remove that line. That was a hack that is not needed anymore

**Comment by matham** [comment]
Ok, great! I removed it and it now compiles properly. So this PR can be merged now.

**Comment by dschreij** [comment]
Thanks for all the work on this @matham!

**Pull request merged**
