### PR TITLE
x11 is needed on the build environment to build with x11 support

### PR DESCRIPTION
**Pull request by matham**
Fixes https://github.com/conda-forge/sdl2-feedstock/issues/13

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matham** [comment]
@conda-forge-admin, please rerender

**Comment by dschreij** [comment]
Thanks again @matham. Does the build number still need to be bumped?

**Comment by matham** [comment]
I added myself and bumped the build number, but it's not yet fixed and I'm still trying to figure out why configure doesn't build with x support.

**Comment by matham** [comment]
From the configure log

```
configure:19656: checking for X
configure:19764: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cpp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -Iinclude -I$SRC_DIR/include -idirafter $SRC_DIR/src/video/khronos  conftest.c
conftest.c:134:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
```

Not sure why this is since we install the x11 dependency.

**Comment by dschreij** [comment]
Check out https://github.com/AnacondaRecipes/r-rgl-feedstock/blob/master/recipe/meta.yaml#L49-L68 which conda often provides for an example for X11 related builds.
Possibly you need to add one of these: (my bets are on libx11-dev)

```
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
```

**Comment by matham** [comment]
I tried adding some of the devels, but no luck. I had inspected the xorg-x11 conda package and it includes the xlib.h file. It must be some kind of reconfiguration? Here is the fuller log from configure:

```
configure:19656: checking for X
configure:19764: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cpp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -Iinclude -I$SRC_DIR/include -idirafter $SRC_DIR/src/video/khronos  conftest.c
In file included from conftest.c:134:0:
$BUILD_PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/X11/Xlib.h:44:10: fatal error: X11/X.h: No such file or directory
 #include <X11/X.h>
          ^~~~~~~~~
compilation terminated.
configure:19764: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define HAVE_DLFCN_H 1
| #define LT_OBJDIR ".libs/"
| #define HAVE_LIBC 1
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_STDIO_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STDDEF_H 1
| #define HAVE_STDARG_H 1
| #define HAVE_MALLOC_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRING_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_WCHAR_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_LIMITS_H 1
| #define HAVE_CTYPE_H 1
| #define HAVE_MATH_H 1
| #define HAVE_FLOAT_H 1
| #define HAVE_ICONV_H 1
| #define HAVE_SIGNAL_H 1
| #define HAVE_M_PI /**/
| #define HAVE_ALLOCA_H 1
| #define HAVE_ALLOCA 1
| #define HAVE_MEMCMP 1
| #define HAVE_STRTOD 1
| #define HAVE_MPROTECT 1
| #define HAVE_MALLOC 1
| #define HAVE_CALLOC 1
| #define HAVE_REALLOC 1
| #define HAVE_FREE 1
| #define HAVE_GETENV 1
| #define HAVE_SETENV 1
| #define HAVE_PUTENV 1
| #define HAVE_UNSETENV 1
| #define HAVE_QSORT 1
| #define HAVE_ABS 1
| #define HAVE_BCOPY 1
| #define HAVE_MEMSET 1
| #define HAVE_MEMCPY 1
| #define HAVE_MEMMOVE 1
| #define HAVE_WCSLEN 1
| #define HAVE_WCSCMP 1
| #define HAVE_STRLEN 1
| #define HAVE_STRCHR 1
| #define HAVE_STRRCHR 1
| #define HAVE_STRSTR 1
| #define HAVE_STRTOL 1
| #define HAVE_STRTOUL 1
| #define HAVE_STRTOLL 1
| #define HAVE_STRTOULL 1
| #define HAVE_ATOI 1
| #define HAVE_ATOF 1
| #define HAVE_STRCMP 1
| #define HAVE_STRNCMP 1
| #define HAVE_STRCASECMP 1
| #define HAVE_STRNCASECMP 1
| #define HAVE_VSSCANF 1
| #define HAVE_VSNPRINTF 1
| #define HAVE_FOPEN64 1
| #define HAVE_FSEEKO 1
| #define HAVE_FSEEKO64 1
| #define HAVE_SIGACTION 1
| #define HAVE_SETJMP 1
| #define HAVE_NANOSLEEP 1
| #define HAVE_SYSCONF 1
| #define HAVE_POLL 1
| #define HAVE_ACOS 1
| #define HAVE_ACOSF 1
| #define HAVE_ASIN 1
| #define HAVE_ASINF 1
| #define HAVE_ATAN 1
| #define HAVE_ATANF 1
| #define HAVE_ATAN2 1
| #define HAVE_ATAN2F 1
| #define HAVE_CEIL 1
| #define HAVE_CEILF 1
| #define HAVE_COPYSIGN 1
| #define HAVE_COPYSIGNF 1
| #define HAVE_COS 1
| #define HAVE_COSF 1
| #define HAVE_EXP 1
| #define HAVE_EXPF 1
| #define HAVE_FABS 1
| #define HAVE_FABSF 1
| #define HAVE_FLOOR 1
| #define HAVE_FLOORF 1
| #define HAVE_FMOD 1
| #define HAVE_FMODF 1
| #define HAVE_LOG 1
| #define HAVE_LOGF 1
| #define HAVE_LOG10 1
| #define HAVE_LOG10F 1
| #define HAVE_POW 1
| #define HAVE_POWF 1
| #define HAVE_SCALBN 1
| #define HAVE_SCALBNF 1
| #define HAVE_SIN 1
| #define HAVE_SINF 1
| #define HAVE_SQRT 1
| #define HAVE_SQRTF 1
| #define HAVE_TAN 1
| #define HAVE_TANF 1
| #define HAVE_ICONV 1
| #define HAVE_SA_SIGACTION 1
| #define HAVE_GCC_ATOMICS 1
| #define SDL_HAPTIC_DISABLED 1
| #define SDL_ASSEMBLY_ROUTINES 1
| #define HAVE_IMMINTRIN_H 1
| #define SDL_VIDEO_DRIVER_DUMMY 1
| #define SDL_AUDIO_DRIVER_DISK 1
| #define SDL_AUDIO_DRIVER_DUMMY 1
| #define SDL_LOADSO_DLOPEN 1
| #define SDL_AUDIO_DRIVER_OSS 1
| /* end confdefs.h.  */
| #include <X11/Xlib.h>
configure:19795: $BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc -o conftest -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I$PREFIX/include -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=${PREFIX}=/usr/local/src/conda-prefix -Iinclude -I$SRC_DIR/include -idirafter $SRC_DIR/src/video/khronos  -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -Iinclude -I$SRC_DIR/include -idirafter $SRC_DIR/src/video/khronos  -Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,-rpath,$PREFIX/lib -L$PREFIX/lib conftest.c -lX11  -lm >&5
configure:19795: $? = 0
configure:19834: result: no
```

**Comment by matham** [comment]
Looks like `{{ cdt('xorg-x11-proto-devel') }}` did the trick. Should be good to (squash and) merge as soon as all pass. Thanks @dschreij

**Comment by dschreij** [comment]
Merged, thanks @matham

**Pull request merged**
