### PR TITLE
Compile on Unix with haptics enabled

### PR DESCRIPTION
**Pull request by traversaro**
With @ooeygui we had problems working with a program that used the SDL haptics part (https://github.com/ros-drivers/joystick_drivers/blob/85c6b56a63ed12239200a371619b644050cf2aad/joy/src/joy.cpp#L386). I could not find in the history why the haptics part was disabled, so I tried to just enable it to see if it was working.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
> I could not find in the history why the haptics part was disabled, so I tried to just enable it to see if it was working.

Indeed, that is working fine, so I think it should be fine to just compile with the haptic part enabled.

**Comment by traversaro** [comment]
> > I could not find in the history why the haptics part was disabled, so I tried to just enable it to see if it was working.
> 
> Indeed, that is working fine, so I think it should be fine to just compile with the haptic part enabled.

All the CI jobs passed. I think this PR is now ready for review. @conda-forge/sdl2

**Review by matham — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @matham ! fyi @ooeygui

**Pull request merged**
