### PR TITLE
Update to 2.0.5; smithy rerender

### PR DESCRIPTION
**Pull request by dschreij**

### CODE REVIEW

**Comment by dschreij** [comment]
@jakirkham I notice py34 is missing in the windows builds, even though I just did a smithy rerender. Is this intentional?

**Comment by jakirkham** [comment]
It is. Python 3.4 was dropped in `conda-smithy` 2.0.0. We (core) agreed to drop that Python version when 3.6 came out, but we were delayed a bit. Hence the brief overlap of 3.4 and 3.6.

**Comment by dschreij** [comment]
Good to know!

Windows builds indeed fail since 2.0.5 with the message

~~~
RC1203: invalid hexadecimal default language ID specified
~~~

this seems to be solved by passing a correct value for the /l parameter, but I have no idea how to do this with CMake. I need to look into this first before this will work.

**Comment by dschreij** [comment]
I filed a bug report at https://bugzilla.libsdl.org/show_bug.cgi?id=3613. Let's hope they pick it up. We can either wait for it, or I can revert back to 2.0.4 (of which builds are already present on conda-forge, so I don't really see the need?).

**Comment by jakirkham** [comment]
Also will need re-rendering with `conda-smithy` 2.2.2 to fix some Windows issues.

**Pull request closed without merging**
